sonar.projectKey=tarzan
sonar.projectName=Tarzan
sonar.sourceEncoding=UTF-8

sonar.sources=apps,packages,prisma,scripts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.test.ts

sonar.tests=apps
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.test.exclusions=**/node_modules/**,**/dist/**

sonar.scm.provider=git
