apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }}
  labels:
    {{- include "tarzan.labels" . | nindent 4 }}
    app.kubernetes.io/name: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "tarzan.selectorLabels" (dict "component" "api" "root" .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
