apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tarzan.fullname" . }}-config
  labels:
    {{- include "tarzan.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: "3000"
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  WEB_ORIGIN: {{ .Values.config.webOrigin | quote }}
  COOKIE_SECURE: {{ .Values.config.cookieSecure | quote }}
