{{- if and .Values.postgres.persistence.enabled .Values.postgres.persistence.static.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "tarzan.fullname" . }}-postgres-pv
  labels:
    {{- include "tarzan.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
spec:
  capacity:
    storage: {{ .Values.postgres.persistence.size }}
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.postgres.persistence.static.reclaimPolicy }}
  storageClassName: {{ .Values.postgres.persistence.static.storageClassName }}
  volumeMode: Filesystem
  hostPath:
    path: {{ .Values.postgres.persistence.static.hostPath }}
    type: DirectoryOrCreate
{{- end }}
