{{- if and .Values.postgres.persistence.enabled (not .Values.postgres.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tarzan.postgresPvcName" . }}
  labels:
    {{- include "tarzan.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  {{- if .Values.postgres.persistence.static.enabled }}
  storageClassName: {{ .Values.postgres.persistence.static.storageClassName }}
  {{- else if .Values.postgres.persistence.storageClassName }}
  storageClassName: {{ .Values.postgres.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}
