apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 03-storage-class.yaml
  - 04-persistent-volume.yaml
  - 05-persistent-volume-claim.yaml
  - 06-postgres-service.yaml
  - 07-postgres-statefulset.yaml
  - 08-api-service.yaml
  - 09-api-deployment.yaml
  - 10-web-service.yaml
  - 11-web-deployment.yaml
  - 12-ingress.yaml
